[project]
name = "sample-pyspark"
version = "0.1.0"
description = "PySpark 3.5.3 project with Java 17 support"
readme = "README.md"
authors = [
    { name = "Mario Lim", email = "mario.lim@openprisetech.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyspark==3.5.3",
]

[project.scripts]
sample-pyspark = "sample_pyspark:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"